#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor -d code office whatsapp web music read VII VIII IX X

bspc config border_width         4
bspc config window_gap          16

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xrandr --size 1920x1080
${HOME}/.fehbg

setxkbmap br
xsettingsd &
compton --blur-background &
mpd &
redshift -l -23.533773:-46.625290 -t 6500K:2500K &
#komorebi &
${HOME}/.config/polybar/launch.sh --cuts

